var PARAMS = {
  preload : {
    audio: [
      "sounds/bikuti-resampled.wav",
      "sounds/budopa-resampled.wav",
      "sounds/daropi-resampled.wav",
      "sounds/golatu-resampled.wav",
      "sounds/kudabi-resampled.wav",
      "sounds/pabiku-resampled.wav",
      "sounds/pigola-resampled.wav",      
      "sounds/tibudo-resampled.wav",
      "sounds/tigobu-resampled.wav",
      "sounds/tudaro-resampled.wav",
      "sounds/block-1-stim.mp3",
      "sounds/block-2-stim.mp3",
      "sounds/block-3-stim.mp3", 
      "sounds/silence.wav"
    ], 
    videos: [
      "video/Pingu_Block1.mp4",
      "video/Pingu_Block2.mp4",
      "video/Pingu_Block3.mp4"
    ],
    images: [
      "images/pingu-wait.png", 
      "images/pingu-listens.png",
      "images/pingu-option-blue.png",
      "images/pingu-option-both.png", 
      "images/pingu-option-purple.png",
      "images/block-1-comp-c.png", 
      "images/block-1-comp-f.png", 
      "images/block-2-comp-c.png", 
      "images/block-2-comp-f.png", 
      "images/block-3-comp-c.png", 
      "images/block-3-comp-f.png"
    ]
  }, 
  conditions : {
    AFC : {
      name: "AFC",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, we are going to see Pingu, who is a little penguin, talk to her family and friends in penguin language. We’re going to watch Pingu as she goes about her day and we’re going to listen carefully to learn her penguin language. In between the videos, we’re going to be shown some pictures asking “what was Pingu doing in the video?” so pay close attention and try your best.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu will say two things, one after the other. Your job is to decide which one of them is a word in the penguin language. Listen carefully to both words, and then choose the one you think is a real word in the penguin language. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "bikuti", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "golatu", category2: "part-word" }
        ],
        list2: [
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pigola", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "tibudo", category2: "part-word" }
        ]
     }
    }, 
    RATING: {
      name: "RATING",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, we are going to see Pingu, who is a little penguin, talk to her family and friends in penguin language. We’re going to watch Pingu as she goes about her day and we’re going to listen carefully to learn her penguin language. In between the videos, we’re going to be shown some pictures asking “what was Pingu doing in the video?” so pay close attention and try your best.",
        test: "Great job! Now we are going to play a game with Pingu. In this game, Pingu the penguin is going to say something and it’s your job to rate how much it sounds like a word in the penguin language. We’re going to have to listen carefully, and use a sliding scale to rate the word. If you think it definitely sounds like a penguin word, you’re going to drag it toward the green check, and if you think it doesn’t sound like a penguin word, you’re going to drag it to the red X. Are you ready to play? Click continue to start", 
      },
      test: {
        list1: [
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tudaro", category1: "word" }
        ],
        list2: [
          { sound1: "tudaro", category1: "word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "budopa", category1: "word" }
        ]
      }
    }, 
    SICR: {
      name: "SICR",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, we are going to see Pingu, who is a little penguin, talk to her family and friends in penguin language. We’re going to watch Pingu as she goes about her day and we’re going to listen carefully to learn her penguin language. In between the videos, we’re going to be shown some pictures asking “what was Pingu doing in the video?” so pay close attention and try your best.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu is going to say some words. After she finishes speaking, your job is to say exactly what Pingu said out loud. To play this game, listen to Pingu very carefully. After Pingu is done talking, say exactly what she said when you see that she is ready to listen. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "pigola", sound2: "tudaro", sound3: "budopa", category: "word" },
          { sound1: "golatu", sound2: "tibudo", sound3: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "daropi", sound2: "pabiku", sound3: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "tibudo", sound2: "daropi", sound3: "pabiku", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "tibudo", sound2: "golatu", sound3: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", sound3: "bikuti", category: "word" },
          { sound1: "golatu", sound2: "pabiku", sound3: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "pabiku", sound2: "golatu", sound3: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "daropi", sound2: "tibudo", sound3: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "pigola", sound3: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "daropi", sound3: "pabiku", category: "part-word" },
          { sound1: "pigola", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "tibudo", sound3: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", sound3: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "golatu", sound3: "tibudo", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", sound3: "pigola", category: "word" },
          { sound1: "daropi", sound2: "pabiku", sound3: "golatu", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", sound3: "bikuti", category: "word" },
          { sound1: "tibudo", sound2: "golatu", sound3: "pabiku", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", sound3: "bikuti", category: "word" },
          { sound1: "golatu", sound2: "pabiku", sound3: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "tudaro", category: "word" },
          { sound1: "pabiku", sound2: "daropi", sound3: "tibudo", category: "part-word" },
          { sound1: "daropi", sound2: "tibudo", sound3: "golatu", category: "part-word" },
          { sound1: "pabiku", sound2: "daropi", sound3: "tibudo", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", sound3: "budopa", category: "word" },
          { sound1: "tudaro", sound2: "pigola", sound3: "budopa", category: "word" }
      ],  
        list2: [
          { sound1: "budopa", sound2: "pigola", sound3: "bikuti", category: "word" },
          { sound1: "tudaro", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "golatu", sound2: "pabiku", sound3: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "daropi", sound2: "pabiku", sound3: "golatu", category: "part-word" },
          { sound1: "tibudo", sound2: "daropi", sound3: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", sound3: "bikuti", category: "word" },
          { sound1: "pigola", sound2: "tudaro", sound3: "budopa", category: "word" },
          { sound1: "daropi", sound2: "tibudo", sound3: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "pigola", sound3: "budopa", category: "word" },
          { sound1: "daropi", sound2: "pabiku", sound3: "golatu", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", sound3: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "golatu", sound3: "tibudo", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "tibudo", sound2: "daropi", sound3: "pabiku", category: "part-word" },
          { sound1: "golatu", sound2: "pabiku", sound3: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", sound3: "budopa", category: "word" },
          { sound1: "pigola", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "tibudo", sound3: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", sound3: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", sound3: "tibudo", category: "part-word" },
          { sound1: "daropi", sound2: "tibudo", sound3: "golatu", category: "part-word" },
          { sound1: "tibudo", sound2: "golatu", sound3: "pabiku", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "pigola", category: "word" },
          { sound1: "pabiku", sound2: "daropi", sound3: "tibudo", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", sound3: "pigola", category: "word" },
          { sound1: "tibudo", sound2: "golatu", sound3: "pabiku", category: "part-word" },
          { sound1: "pigola", sound2: "budopa", sound3: "tudaro", category: "word" },
          { sound1: "pabiku", sound2: "golatu", sound3: "tibudo", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", sound3: "tudaro", category: "word" },
          { sound1: "bikuti", sound2: "tudaro", sound3: "budopa", category: "word" },
          { sound1: "golatu", sound2: "tibudo", sound3: "daropi", category: "part-word" }
      ]
      }
    }, 
    SICR2: {
      name: "SICR2",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, we are going to see Pingu, who is a little penguin, talk to her family and friends in penguin language. We’re going to watch Pingu as she goes about her day and we’re going to listen carefully to learn her penguin language. In between the videos, we’re going to be shown some pictures asking “what was Pingu doing in the video?” so pay close attention and try your best.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu is going to say some words. After she finishes speaking, your job is to say exactly what Pingu said out loud. To play this game, listen to Pingu very carefully. After Pingu is done talking, say exactly what she said when you see that she is ready to listen. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "daropi", sound2: "pabiku", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "golatu", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "golatu", sound2: "pabiku", category: "part-word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" }
          ],
        list2: [
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "daropi", sound2: "pabiku", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "golatu", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "golatu", sound2: "pabiku", category: "part-word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" }
          ]
      }
    }
  }
}
