var PARAMS = {
  preload : {
    audio: [
      "sounds/bikuti-resampled.wav",
      "sounds/budopa-resampled.wav",
      "sounds/daropi-resampled.wav",
      "sounds/golatu-resampled.wav",
      "sounds/kudabi-resampled.wav",
      "sounds/pabiku-resampled.wav",
      "sounds/pigola-resampled.wav",      
      "sounds/tibudo-resampled.wav",
      "sounds/tigobu-resampled.wav",
      "sounds/tudaro-resampled.wav",
      "sounds/block-1-stim.mp3",
      "sounds/block-2-stim.mp3",
      "sounds/block-3-stim.mp3", 
      "sounds/silence.wav"
    ], 
    videos: [
      "video/Pingu_Block1.mp4",
      "video/Pingu_Block2.mp4",
      "video/Pingu_Block3.mp4"
    ],
    images: [
      "images/pingu-wait.png", 
      "images/pingu-listens.png",
      "images/pingu-option-blue.png",
      "images/pingu-option-both.png", 
      "images/pingu-option-purple.png",
      "images/block-1-comp-c.png", 
      "images/block-1-comp-f.png", 
      "images/block-2-comp-c.png", 
      "images/block-2-comp-f.png", 
      "images/block-3-comp-c.png", 
      "images/block-3-comp-f.png"
    ]
  }, 
  conditions : {
    AFC : {
      name: "AFC",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, you are going to see Pingu, the little penguin, talking to her family and friends in the penguin language. Watch as Pingu goes about her day and listen carefully to the penguin language. Between videos, you will be asked comprehension questions about what Pingu was doing, so make sure that you are paying attention. Click continue start watching the video.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu will say two things, one after the other. Your job is to decide which one of them is a word in the penguin language. Listen carefully to both words, and then choose the one you think is a real word in the penguin language. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "bikuti", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "golatu", category2: "part-word" }
        ],
        list2: [
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "pigola", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "daropi", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "golatu", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "budopa", category1: "word", sound2: "tibudo", category2: "part-word" },
          { sound1: "pabiku", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "tudaro", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "bikuti", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "tibudo", category1: "part-word", sound2: "pigola", category2: "word" },
          { sound1: "pabiku", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "bikuti", category1: "word", sound2: "daropi", category2: "part-word" },
          { sound1: "golatu", category1: "part-word", sound2: "tudaro", category2: "word" },
          { sound1: "tibudo", category1: "part-word", sound2: "bikuti", category2: "word" },
          { sound1: "pigola", category1: "word", sound2: "pabiku", category2: "part-word" },
          { sound1: "budopa", category1: "word", sound2: "golatu", category2: "part-word" },
          { sound1: "daropi", category1: "part-word", sound2: "budopa", category2: "word" },
          { sound1: "tudaro", category1: "word", sound2: "tibudo", category2: "part-word" }
        ]
     }
    }, 
    RATING: {
      name: "RATING",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, you are going to see Pingu, the little penguin, talking to her family and friends in the penguin language. Watch as Pingu goes about her day and listen carefully to the penguin language. Between videos, you will be asked comprehension questions about what Pingu was doing, so make sure that you are paying attention. Click continue to start watching the video.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu will say something, and your job is to rate how much it sounds like a word in the penguin language. Listen carefully to what Pingu says, and then use the sliding scale on the screen to rate it. The scale goes from ‘not at all like a penguin word’ to ‘definitely a penguin word'. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tudaro", category1: "word" }
        ],
        list2: [
          { sound1: "tudaro", category1: "word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "budopa", category1: "word" },
          { sound1: "bikuti", category1: "word" },
          { sound1: "golatu", category1: "part-word" },
          { sound1: "tudaro", category1: "word" },
          { sound1: "daropi", category1: "part-word" },
          { sound1: "pigola", category1: "word" },
          { sound1: "pabiku", category1: "part-word" },
          { sound1: "tibudo", category1: "part-word" },
          { sound1: "budopa", category1: "word" }
        ]
      }
    }, 
    SICR: {
      name: "SICR",
      instructions: {
        exposure: "Today we are going to watch some fun videos and play a game. In the videos, you are going to see Pingu, the little penguin, talking to her family and friends in the penguin language. Watch as Pingu goes about her day and listen carefully to the penguin language. Between videos, you will be asked comprehension questions about what Pingu was doing, so make sure that you are paying attention. Click continue to start watching the video.",
        test: "Great job! Now you and Pingu are going to play a game. In this game, Pingu is going to say some words. After she finishes speaking, your job is to say exactly what Pingu said out loud. To play this game, listen to Pingu very carefully. After Pingu is done talking, say exactly what she said when you see that she is ready to listen. Are you ready to play? Click continue to start.", 
      },
      test: {
        list1: [
          { sound1: "daropi", sound2: "pabiku", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "golatu", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "golatu", sound2: "pabiku", category: "part-word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" }
          ],
        list2: [
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "daropi", sound2: "pabiku", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "golatu", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "tudaro", category: "word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "tudaro", sound2: "budopa", category: "word" },
          { sound1: "golatu", sound2: "pabiku", category: "part-word" },
          { sound1: "pabiku", sound2: "golatu", category: "part-word" },
          { sound1: "bikuti", sound2: "tudaro", category: "word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "golatu", sound2: "daropi", category: "part-word" },
          { sound1: "bikuti", sound2: "budopa", category: "word" },
          { sound1: "tibudo", sound2: "golatu", category: "part-word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "pigola", sound2: "bikuti", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "tibudo", sound2: "pabiku", category: "part-word" },
          { sound1: "tudaro", sound2: "pigola", category: "word" },
          { sound1: "pabiku", sound2: "daropi", category: "part-word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" },
          { sound1: "daropi", sound2: "tibudo", category: "part-word" },
          { sound1: "budopa", sound2: "pigola", category: "word" },
          { sound1: "budopa", sound2: "bikuti", category: "word" }
          ]
      }
    }
  }
}
